### ISSUE TITLE
Comparison with vsivsi:job-collection

### ISSUE THREAD

**Issue by sebakerckhof** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#1]
Nice work!

How does this package compare to  vsivsi:job-collection ( https://github.com/vsivsi/meteor-job-collection )?
At first glance, it seems quite similar, so I suspect there's certain reasons why you choose to write this package and it'd be interesting to know what those reasons are for those of us having to choose between the two.

**Comment by msavin** [comment]
Thanks for the question! It's a little hard to capture the difference between the two, or why one would use one or the other, especially because MJC is a good solution. 

I haven't really looked into it until you mentioned it. I did see it while researching the options, but I was instantly turned off by the fact that it works as a collection and is isomorphic. I wanted a package that is server only and makes everything including data management _invisible_. 

My goal with SJ was to make it as simple and friendly as possible. The interface is one that anyone can quickly understand and start playing with:

```javascript
Jobs.add("sendReminderEmail", "john@smith.com", "The future is here!", {
    in: {
        days: 1,
    }
});
```

The down side of that is that the scheduling options are a bit limited, but if it fits your needs it should work great, and I am considering to expand them.

**Comment by skemb321** [comment]
In my opinion, MJC is quite complicated. I actually chose percolate:synced-cron over it for message queues. Maybe my decision was "weird" but I really thought MJC was very complicated at that time. But this SJ is much simpler.

**Comment by luixal** [comment]
Yep, the downside of MJC is the complication to get it running. The good thing is that you can do pretty much anything.

In my case, I have to keep using MJC right now because of the repeating jobs (90% of my jobs run repeteadly over time).

**Comment by msavin** [comment]
@luixal I hear that, this might be a configuration vs convention type of thing. I wonder, would something like this feel fit your needs?

```Jobs.repeat(function () {
	console.log("Good morning sir")
}, {
	day: "Monday",
	hour: 9
})```
