### ISSUE TITLE
Repeating a job

### ISSUE THREAD

**Issue by Twisterking** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#7]
Thanks for yet another very nice package @msavin!

I would love to use `SteveJobs` for my background tasks but I would desperately need one thing: **repetition**. I need to be able to repeat a job every xy amount of time indefinitely - like checking a remote server for certain updates every 24h.

Could you implement such a feature?

**Comment by msavin** [comment]
Yes - thinking about it. One consideration is to make a completely separate package for it:

**Insanity**
Doing the same thing over and over but expecting different results 

I haven't encountered this use case though. What would be the most important things for you here?

**Comment by Twisterking** [comment]
Again, for example:
My app has to receive certain updates from several remote servers run by my customers. So I need a nice way to run these updates daily at approx the same time (during the night - less load on the server) but not in parallel but one after the other.
It would be great if one of these jobs doesn't run properly (for example if one of the remote servers is not reachable at the point) it tries again automatically every 5mins or so.
Something like this ... Does this make sense for you? :)

**Comment by msavin** [comment]
You're making a bit more sense, yes.

So far it sounds like:
 - tasks should be able to execute simultaneously, but it's okay if they
run consecutively
 - tasks should run at a specific time (but what if it's delayed by seconds
or 5-10 minutes?)
 - there should be a way to re-run the job in specific cases (such as an
API call not returning expected data)
 - if retries fail X times, it should stop running until the next turn and
perhaps alert the application owner
 - if server restarts, it should re-try again in case it was a re-deploy

Feel free to add. It would be great to get input from more people as well.

**Comment by Twisterking** [comment]
Nope your lists sounds perfectly fine!

1.) yes, choosing between running jobs in parallel or in series would be awesome. there just might be jobs which are kinda CPU intensive or maybe depend on each other, so in these cases in series would be much better than in parallel.
2.) for my use case a delay of couple of seconds/minutes is just fine, doesn't matter.
3.) automatical retry would be pretty much a must yes.
4.) yes please!
5.) would be great sure.

**Comment by sunlee-newyork** [comment]
Presenting my current setup of repeating jobs for another use case (hope it comes in handy):
I'm using `kelektiv/node-cron` at server Meteor.startup and scheduling 4 daily jobs at hourly intervals. I add special job boolean properties on my collection documents to check if they've been processed, since cron is reinitiated at every server restart (e.g. deploy).

Example:
```
// NOTE: Daily booking followups @7AM EST
if (Meteor.isServer) {
	Meteor.startup(() => {
		console.log("==> Configure followup emails cron job...");
		const followupEmailsJob = new CronJob({
			cronTime: '00 00 11 * * *',
			onTick: Meteor.bindEnvironment(() => {
				Meteor.call("sendFollowupEmails");
		                // Here the method finds all documents in a collection that have followupSent === false and sends the email, then marks it followupSent === true
			}),
			onComplete: () => {
		                // Should not stop, since this is a forever repeating job
				Raven.captureMessage("followup email cron job stopped. Investigation required.");
			},
			start: true,
			timeZone: 'Universal',
			runOnInit: true // Should always run on init since server constantly restarts from deploys
		});

		if (followupEmailsJob.running) console.log("==> Configured followup email cron job.");
		else {
			console.error("==> Followup email cron failed to initiate.");
			Raven.captureMessage("Followup email cron failed to initiate.");
		}
	});
}
```

**Comment by msavin** [comment]
@sunlee-newyork thanks - it's nice to see how people are doing it

I've thought about it a bit more.. I think there's a really easy way to pop this into the package.

First, we define our jobs as usual: 

```javascript
Jobs.register({
    sendReminderEmail: function (to, content) {
        Email.send({
            to: to,
            from: "no-reply@jobs.com",
            subject: "Your Reminder",
            content: content,
        })
    }
});
```
But then, instead of running Jobs.add, we run Jobs.repeat: 

```javascript
Jobs.repeat("sendReminderEmail", "john@smith.com", "Hello again!", {
    in: {
        hours: 1
    } 
})
```

  - Since the job name is used as the id, each job can only have one repeat on it, but the repeat settings would be very flexible 
 - Even though the job can only have one `repeat` on it, it can still be called regularly with `Jobs.add`
 - In case of code errors, it would stop until the server restarts. That way, if there is an error in your code, the jobs will retry once you re-deploy.
 - In case of other errors, it will have provide you with different methods for re-trying the jobs. 

In a way, it would be like a recursive function. It would run, then reschedule itself to run again based on your settings. I'm thinking the rescheduling time be set after the job executes.  That way, the job can essentially say, "run this job, then once its ready run it again in one hour. If it failed, run it once I re-deploy or retry in 5 minutes."

**Comment by luixal** [comment]
In the way I'm using repeated jobs, the parameters part is not needed: the job can ask for its parameters (usually from mongo) by itself. In fact, when base parameters are different, I consider it a different job.

> Since the job name is used as the id, each job can only have one repeat on it, but the repeat settings would be very flexible

I have just noticed that we have different concepts on this: for me, the `sendReminderEmail` is a **type** of job. Each execution is what I call a `job` (a job execution, really). This is, the way I was seeing it a job is a document that has its own autogenerated `_id` and kind of a `type` field which value is `sendReminderEmail`.

That's why I talked about laterjs for repetition, because it allows you to do something like this:

```javascript
let schedule = later.parse.text('every 1 hour');
console.log(later.schedule(schedule).next());
// output:
// Thu Nov 02 2017 10:57:18 GMT+0100 (Hora estándar romance)
console.log(later.schedule(schedule).next(3));
// output:
// [ Thu Nov 02 2017 10:58:13 GMT+0100 (Hora estándar romance),
//    Thu Nov 02 2017 11:00:00 GMT+0100 (Hora estándar romance),
//    Thu Nov 02 2017 12:00:00 GMT+0100 (Hora estándar romance) ]
```

So, if a job has a recurrent schedule, you just need to get the next execution datetime from laterjs and add a new job run at the end of the current job execution.

In any case, I find the `in` and `on` convention quite confusing :(

**Comment by Twisterking** [comment]
Agreed about the `in` and `on` part. Maybe `in` and `at` would be better? not sure ...

**Comment by luixal** [comment]
Or maybe the same `in`, `on` or `at`, but inside a `repeat` field.

**Comment by msavin** [comment]
What do you guys think about this:

```javascript
Jobs.register({
	syncWithAPI: function (userId) {
		if (userId) {
			API.doMagic(userId);
		} else {
			API.doMagic();
		}
	}
})

Jobs.repeat("syncWithAPI", {
	hour: 1,
	minute: 30
})
```

That way, it runs every hour and a half. You can also schedule it sooner with Jobs.run(). Arguments could be passed into function, or not.

As for timing, the idea I am thinking is, the function will run, then:
 - if the job succeeds, it will reschedule itself
 - if the job fails, it will be marked as fail and re-run when server restarts

The rescheduling would happen after the function is executed. This means it does not run exactly every hour and a half, it runs every hour and half plus the execution time. Good or bad?

-----

The thing that's missing is the option to run it on a specific time. Maybe that could/should be done with a different API? I'd go with `Jobs.routine` but all the other commands are verbs (register, run, repeat).

**Comment by luixal** [comment]
> As for timing, the idea I am thinking is, the function will run, then:
> 
> * if the job succeeds, it will reschedule itself
> * if the job fails, it will be marked as fail and re-run when server restarts
> The rescheduling would happen after the function is executed. This means it does not run exactly every hour and a half, it runs every hour and half plus the execution time. Good or bad?

Maybe someone wants the job to be re-scheduled even if it fails (i.e: a REST API you're syncing data from time to time), I think a `rescheduleOnFailure` boolean param would be great for that and doesn't make the implementation more complex. Maybe something like this:

```javascript
Job.repeat(
  'syncWithAPI',
  {
    when: {
      hour: 1,
      minute: 30
    },
    rescheduleOnFailure: true
  }
);
```

> The thing that's missing is the option to run it on a specific time. Maybe that could/should be done with a different API? I'd go with Jobs.routine but all the other commands are verbs (register, run, repeat).

To support this and more complex syntax (i.e: "first monday at 9am")I would use `laterjs`. To avoid dependencies, maybe the possibility to pass a custom function `getNextExecution(jobOptions)` that returns an specific timestamp (or Date object) would be enough to people that wants more specific stuff.

I'm thinking in something like this:

```javascript
Job.repeat(
  'syncWithAPI',
  {
    when: {
      getNextExecution: function(jobOptions) {
        // you can return a fixed moment in time:
        return new Date('2017-12-31 23:59');
        // or calculate it using a third party solution:
        return later.schedule(later.parse.text('every first monday at 9am')).next();
      }
    },
    rescheduleOnFailure: true
  }
);
```

This way it's quite easy to make another packages that adds support for `laterjs` and other similar packages to this one.

What do you think?

**Comment by vfonic** [comment]
Hi @msavin!

_Not sure if this is the best place to ask._

I see there are some commits on `master` that added `Jobs.reschedule`. Does this mean the package now supports rescheduling/recurring jobs?

Thanks!

**Comment by msavin** [comment]
Not ready yet - hoping to get to it before the year ends :)

**Comment by msavin** [comment]
So - this did not make the cut for 2.0 - but is now achievable: 

Quick example: 

```javascript
Jobs.register({
	"sendEmail": function () {
		var self = this;
		var apiCall = HTTP.post(/* ... */)

		if (apiCall.statusCode === 200) {
			self.reschedule({
				in: {
					minutes: 5
				}
			})
		} else {
			self.failure(); // will retry when new servers takes over
		}
	}
})
```


More info: https://github.com/msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue/wiki#jobsregister
